### PR TITLE
fix: Normalize padding in PaperContainer body

### LINKED ISSUE #1336: Extra page paddings on space page
Extra top padding appeared on the space page. Most likely after this change: https://github.com/operately/operately/pull/1328.

Screenshot 2024-10-14 at 14 52 24

### PR DESCRIPTION
**Pull request by markoa**
Fixes #1336.

### CODE REVIEW

File: assets/js/components/PaperContainer/index.tsx [hunk 1]
```diff
@@ -63,10 +63,28 @@ export function Root({ size, children, className, fluid = false }: RootProps): J
...
+};
+
+export function Body({
+  children,
+  minHeight = "none",
+  className = "",
+  noPadding = false,
+  backgroundColor = "bg-surface",
+}) {
+  const { size } = React.useContext(Context);
```
Comment (markoa) [inline assets/js/components/PaperContainer/index.tsx:81]: I tried to replace this with a tailwind one-liner but couldn't make it work

Comment (shiroyasha) [reply assets/js/components/PaperContainer/index.tsx:81]: What was the limiting factor?

**Comment by shiroyasha** [comment]
Awesome! Thanks for the quick fix. Shipping 🚢

File: assets/js/components/PaperContainer/index.tsx (hunk 1 above)
Comment (markoa) [reply assets/js/components/PaperContainer/index.tsx:81]: if I'd translate the paddings hash into `sm:xxx lg:zzz` etc then it would work on 1-2 screen sizes but not on the rest, and it have side effects like the top of spaces nav bar would get out of position etc.
